name = "manager"
version = "0.1.0"
description = "A basic Theater actor"
component_path = "/Users/colinrozzi/work/actors/manager/target/wasm32-unknown-unknown/release/manager.wasm"
init_state = "/Users/colinrozzi/work/actors/manager/init.json"

[interface]
implements = "ntwk:theater/actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

[[handlers]]
type = "supervisor"
config = {}
