package ntwk:theater;

world hello-world {
    import runtime;
    export actor;
    export message-server-client;

    import timing;
    import supervisor;
    import message-server-host;
    import store;
}
